plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.runtime' version '2.0.1'
    id 'com.coditory.manifest' version '1.1.0'
    id 'antlr'
}

version = '1.0.4'

group = 'nu.mine.mosher.graph'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 21
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri('https://public:\u0067hp_fya6Kseu3XOBMg2icbg7f1LP6ZFYjj35v4Zj@maven.pkg.github.com/cmosher01/*')
    }
}

dependencies {
    implementation 'nu.mine.mosher.io:log-files:latest.release'
    implementation 'org.slf4j:jcl-over-slf4j:latest.release'
    implementation 'org.slf4j:log4j-over-slf4j:latest.release'
    implementation 'org.slf4j:jul-to-slf4j:latest.release'
    implementation 'org.slf4j:slf4j-api:latest.release'
    implementation 'ch.qos.logback:logback-classic:latest.release'
    antlr 'org.antlr:antlr4:latest.release'
    implementation 'org.neo4j.driver:neo4j-java-driver:latest.release'
}

application {
    mainModule = 'nu.mine.mosher.graph.digred'
    mainClass = 'nu.mine.mosher.graph.digred.Digred'
}

jar {
    manifest {
        attributes(
            'Specification-Version': manifest.attributes.get('Implementation-Version'),
            'Implementation-Version': manifest.attributes.get('Implementation-Version').toString()+"+"+manifest.attributes.get('SCM-Commit-Hash').toString()
        )
    }
}

def os = org.gradle.internal.os.OperatingSystem.current()
println "detected OS: ${os}"

runtime {
    jpackage {
        if (os.windows) {
            installerOptions += [
                '--win-dir-chooser',
                '--win-menu',
                '--win-shortcut',
                '--verbose'
            ]
        } else if (os.linux) {
            installerOptions += [
                '--linux-shortcut',
                '--verbose'
            ]
        }
    }
}

assemble {
    dependsOn tasks.jpackage
}

generateGrammarSource {
    packageName = 'nu.mine.mosher.graph.digred.schema'
    arguments += ['-long-messages']
    outputDirectory = layout.buildDirectory.dir("generated/sources/grammar/antlr/main").get().asFile
}

sourceSets {
    main {
        java {
            srcDir layout.buildDirectory.dir("generated/sources/grammar/antlr/main").get().asFile
        }
    }
}
