plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.jlink' version '2.25.0'
    id 'com.coditory.manifest' version '1.1.0'
    id 'antlr'
    id 'org.gradlex.extra-java-module-info' version '1.8'
}

version = '1.0.3'

group = 'nu.mine.mosher.graph'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 21
    }
    modularity.inferModulePath = true
}

extraJavaModuleInfo {
    deriveAutomaticModuleNamesFromFileNames = true
}

repositories {
    mavenCentral()
    maven {
        url = uri('https://public:\u0067hp_fya6Kseu3XOBMg2icbg7f1LP6ZFYjj35v4Zj@maven.pkg.github.com/cmosher01/*')
    }
}

dependencies {
    implementation 'nu.mine.mosher.io:log-files:latest.release'
    implementation 'org.slf4j:jcl-over-slf4j:latest.release'
    implementation 'org.slf4j:log4j-over-slf4j:latest.release'
    implementation 'org.slf4j:jul-to-slf4j:latest.release'
    implementation 'org.slf4j:slf4j-api:latest.release'
    implementation 'ch.qos.logback:logback-classic:latest.release'
    antlr 'org.antlr:antlr4:latest.release'
    implementation 'org.neo4j.driver:neo4j-java-driver:latest.release'
}

application {
    mainModule = 'nu.mine.mosher.graph.digred'
    mainClass = 'nu.mine.mosher.graph.digred.Digred'
}

ext.antlrPackage = 'nu.mine.mosher.graph.digred.schema'

jar {
    manifest {
        attributes(
            'Specification-Version': manifest.attributes.get('Implementation-Version'),
            'Implementation-Version': manifest.attributes.get('Implementation-Version').toString()+"+"+manifest.attributes.get('SCM-Commit-Hash').toString()
        )
    }
}

def os = org.gradle.internal.os.OperatingSystem.current()
println "detected OS: ${os}"

jlink {
    mergedModule {
        additive = true
        requires 'org.slf4j'
        excludeProvides servicePattern: 'org.neo4j.driver.internal.*'
        excludeProvides servicePattern: 'reactor.blockhound.*'
    }
    jpackage {
        if (os.windows) {
            installerOptions += [
                '--win-dir-chooser',
                '--win-menu',
                '--win-shortcut'
            ]
        } else if (os.linux) {
            installerOptions += [
                '--linux-shortcut'
            ]
        }
        installerOptions += [ '--verbose' ]
    }
}

assemble {
    dependsOn tasks.jpackage
}

generateGrammarSource {
    arguments += ['-long-messages', '-package', antlrPackage]
    outputDirectory = new File("${project.buildDir}/generated/sources/grammar/antlr/main")
}

sourceSets {
    main {
        java {
            srcDir "${buildDir.absolutePath}/generated/sources/grammar/antlr/main"
        }
    }
}
